project_id = "vmusmbuofkhzmtoqdhqc"

[functions.aws-proxy]
verify_jwt = false

[functions.match-patient]
verify_jwt = false

[functions.aws-webhook]
verify_jwt = false

[functions.analyze-exam]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.notify-admin-acceptance]
verify_jwt = false

[functions.expire-invitations]
verify_jwt = false
